name: Discord Release Notify
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Discord
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          REPO: ${{ github.repository }}
          TAG:  ${{ github.event.release.tag_name }}
          URL:  ${{ github.event.release.html_url }}
        run: |
          # ← ここから下、スペースでインデント（タブ禁止）
          NAME="${REPO#*/}"
          TITLE="New release: ${NAME} ${TAG}"

          # jq で JSON を安全に生成（クオート問題を根絶）
          jq -n \
            --arg title "$TITLE" \
            --arg url   "$URL" \
            '{embeds:[{title:$title, url:$url, color:16098851}]}' \
          | curl -sS -H "Content-Type: application/json" -d @- "$WEBHOOK"
