name: Discord Release Notify
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Discord
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          REPO: ${{ github.repository }}
          TAG:  ${{ github.event.release.tag_name }}
          URL:  ${{ github.event.release.html_url }}
        run: |
          printf '{"content":"📦 New release **%s %s** — %s"}' "$REPO" "$TAG" "$URL" \
          | curl -sS -H "Content-Type: application/json" -d @- "$WEBHOOK"
